<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOqOPEij\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOqOPEij/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOqOPEij.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOqOPEij\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOqOPEij\App_KernelDevDebugContainer([
    'container.build_hash' => 'OqOPEij',
    'container.build_id' => 'ec4829d4',
    'container.build_time' => 1680371009,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOqOPEij');
