<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEpBvkD0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEpBvkD0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEpBvkD0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEpBvkD0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEpBvkD0\App_KernelDevDebugContainer([
    'container.build_hash' => 'EpBvkD0',
    'container.build_id' => '4239e12f',
    'container.build_time' => 1680960051,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEpBvkD0');
