<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGrMKLSt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGrMKLSt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGrMKLSt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGrMKLSt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGrMKLSt\App_KernelDevDebugContainer([
    'container.build_hash' => 'GrMKLSt',
    'container.build_id' => 'd8a568fb',
    'container.build_time' => 1681049469,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGrMKLSt');
